<?php 
$get_campaigns = Mage::helper('pushassist')->get_campaigns();
$check_api_key=Mage::app()->getStore()->getConfig('pushassistsection/general/apikey');
$check_secret_key=Mage::app()->getStore()->getConfig('pushassistsection/general/secretkey');
$account_response = Mage::helper('pushassist')->get_account_details();
if(isset($account_response['account_name'])){
$account_url='https://'.$account_response['account_name'].'.pushassist.com/dashboard/';
}
if($check_api_key!='' && $check_secret_key != '' && (!isset($account_response['error'] )) && $account_response ) {
if( count($get_campaigns) > 0){ 
//print_r($get_segement);
?>
<div id="Psidebar" >
  <ul>
   <!-- <li><a href="<?php //echo $this->getUrl('*/pushassist_createaccount'); ?>">Create an Account</a></li>-->
    <li><a href="<?php echo $this->getUrl('*/pushassist_dashboard'); ?>"><?php echo $this->__('Dashboard')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_notificationmain'); ?>"><?php echo $this->__('Notifications')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_notificationsend'); ?>"><?php echo $this->__('Send Notification')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_segments'); ?>"><?php echo $this->__('Segments')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_createsegments'); ?>"><?php echo $this->__('Create Segments')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_subscribers'); ?>"><?php echo $this->__('Subscribers')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_settings'); ?>"><?php echo $this->__('Settings')?></a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_campaign'); ?>"><?php echo $this->__('Campaigns')?></a></li>
   </ul>
  </div>
<!-- Content Start -->
    <div id="pushassist" class="content dashboard clearfix">
        <!-- Start Page Header -->
        <div class="page-header">
            <h1 class="title"><?php echo $this->__('Campaigns');?></h1>
        </div>
        <!-- End Page Header -->

        <!-- Container Start -->
        <div class="container-widget clearfix">
           

            <!-- Project Stats Start -->
           <div class="col-md-6" style="width:54%">
            <div class="panel panel-default">

                <div class="panel-body">
                   
                    <p><strong><?php echo $this->__('Campaigns');?></strong></p>
                    <p class="margin-b-20">	
		      <?php echo $this->__('Following screenshot shows how you can create and schedule a campaign.');?>
		      <strong><?php echo $this->__('This feature is available in premium plans.');?> </strong> </p>
                    <p class="align-center margin-b-25">
                          <a href="<?php echo $account_url;?>" target="_blank" class="btn btn-default margin-t-0"><?php echo $this->__('Upgrade to Premium');?></a>
                    </p>
                    <div class="margin-t-15 image_wrapper">
 
                        <img src="<?php echo $this->getSkinUrl('pushassist/campaign.png') ?>" alt="Campaign Notification">
                    </div>

                </div>
            </div>
        </div>
            <!-- Project Stats End -->
        </div>
        <!-- Container End -->
    </div>
    <!-- Content End -->
<?php }else{ 
	    echo $this->__('No result found.');
}
}else{
 Mage::app()->getResponse()->setRedirect(Mage::helper("adminhtml")->getUrl("adminhtml/pushassist_createaccount/index/"));
} ?>
