<?php 
$check_api_key=Mage::app()->getStore()->getConfig('pushassistsection/general/apikey');
$check_secret_key=Mage::app()->getStore()->getConfig('pushassistsection/general/secretkey');
$account_response = Mage::helper('pushassist')->get_account_details();
$account_url='https://'.$account_response['account_name'].'.pushassist.com/dashboard/';

if($check_api_key!='' && $check_secret_key != '' && $account_response['error'] == '' && $account_response) {
?>


<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
<div id="Psidebar" >
  <ul>
    <li><a href="<?php echo $this->getUrl('*/pushassist_createaccount'); ?>">Create an Account</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_dashboard'); ?>">Dashboard</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_notificationmain'); ?>">Notifications</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_notificationsend'); ?>">Send Notification</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_segments'); ?>">Segments</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_createsegments'); ?>">Create Segment</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_subscribers'); ?>">Subscribers</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_campaign'); ?>">Campaigns</a></li>
  </ul>
  </div>
<!-- Content Start -->
    <div id="pushassist" class="content clearfix">
        <!-- Start Page Header -->
        <div class="page-header">
            <h1 class="title">Create a New Segment</h1>
        </div>
        <!-- End Page Header -->

        <!-- Container Start -->
        <div class="container-widget clearfix">
            <div class="alert alert-danger alert-dismissable" id="pushassist_error" style="display: none"></div>
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="<?php echo $this->getUrl('*/*/addsegments'); ?>" method="post" autocomplete="off" id="create_segment_form" name="create_segment_form" enctype="multipart/form-data">                            
                            <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                            <div class="form-group">
                                <label class="col-sm-3 control-label form-label">Segment Name</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="title" name="title" placeholder="Enter Segment Name here" maxlength="40" required="required" />
                                    <span class="pull-right">Segment Name Limit 40 Characters.Example segment name:Google</span>
                                </div>
                            </div>
                            
			    <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-1 col-xs-3">
                                    <button type="submit" class="btn btn-default">Send</button>
                                </div>
			    </div>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-6-->

	   <div class="col-md-6 dummy-notification shadow panel panel-default">

		  <p class="h5 pb15"><strong>How to Implement Segments for your Push Notification Subscribers</strong></p>

		  <div class="widget shadow dummy-notification-inner-wrapper pb15">
		      <p><strong>Step 1 :</strong> Create a new segment. Go to Create Segments</p>

		      <p><strong>Step 2 :</strong> Copy the following JavaScript code and paste it on your site page(s).</p>

		      <p class="margin-t-20"><strong>Subscribe for Single Segment</strong></p>
		      <p>
			  &lt;script&gt;
			  <br>
			  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var _pa = [];<br>
			  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; _pa.push('segmentname');
			  <br>
			  &lt;/script&gt;
		      </p>

		      <p class="margin-t-20"><strong>Subscriber for Multiple Segments</strong></p>
		      <p>
			  &lt;script&gt;
			  <br>
			  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var _pa = [];<br>
			  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; _pa.push('segmentname1', 'segmentname2');
			  <br>
			  &lt;/script&gt;
		      </p>
		  </div>
           </div>

        </div>
        <!-- Container End -->
    </div>
    <!-- Content End -->
<?php }else{
Mage::app()->getResponse()->setRedirect(Mage::helper("adminhtml")->getUrl("adminhtml/pushassist_createaccount/index/"));

} ?>    
   
	  


