<?php 
$check_api_key=Mage::app()->getStore()->getConfig('pushassistsection/general/apikey');
$check_secret_key=Mage::app()->getStore()->getConfig('pushassistsection/general/secretkey');
$dashboard_response = Mage::helper('pushassist')->get_dashboard();
$account_response = Mage::helper('pushassist')->get_account_details();
$account_url='https://'.$account_response['account_name'].'.pushassist.com/login/';

if($check_api_key!='' && $check_secret_key != '' && $account_response['error'] == '' && $account_response) {

?>
<!-- Content Start -->
<div id="Psidebar" >
 <ul>
    <li><a href="<?php echo $this->getUrl('*/pushassist_createaccount'); ?>">Create an Account</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_dashboard'); ?>">Dashboard</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_notificationmain'); ?>">Notifications</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_notificationsend'); ?>">Send Notification</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_segments'); ?>">Segments</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_createsegments'); ?>">Create Segment</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_subscribers'); ?>">Subscribers</a></li>
    <li><p><?php echo $account_response['planType'];?>&nbsp;&nbsp;<a href="<?php echo $account_url;?>" target="_blank">Upgrade Now</a> </p></li>
    <li><p>You have <?php echo $account_response['subscribers_remain'];?> subsribers left</p></li>

  </ul>
  </div>

    <div id="pushassist" class="content dashboard clearfix">
  
        <!-- Start Page Header -->
        <div class="page-header">
            <h1 class="title">Dashboard</h1>
        </div>
        <!-- End Page Header -->

        <!-- Container Start -->
        <div class="container-widget clearfix">
            <!-- Top Stats Start -->
            <div class="col-md-12">
                <ul class="topstats clearfix">
                    <li class="col-xs-6 col-lg-2">
                        <span class="title"><i class="fa fa-send"></i> Total Delivered </span>
                        <h3><?php echo $dashboard_response['total_delivered']; ?></h3>
                        <span class="diff">
						<?php if ($dashboard_response['delivered_change'] == 'negative') { ?>
						<b class="color-down"><i class="fa fa-caret-down"></i> <?php echo $dashboard_response['delivered_percentage']; ?>
						<?php }
						if ($dashboard_response['delivered_change'] == 'positive') { ?>
						<b class="color-up"><i class="fa fa-caret-up"></i> <?php echo $dashboard_response['delivered_percentage']; ?>
							<?php } ?>%

						
						</b> from last week</span>
                    </li>

                    <li class="col-xs-6 col-lg-2">
                        <span class="title"><i class="fa fa-check-square-o"></i> Total Clicks </span>
                        <h3 class="color-up"><?php echo $dashboard_response['total_clicks']; ?></h3>
                        <span class="diff">
                            <?php if ($dashboard_response['clicks_change'] == 'negative') { ?>
                            <b class="color-down"><i class="fa fa-caret-down"></i> <?php echo $dashboard_response['clicks_percentage']; ?>
                                <?php } if ($dashboard_response['clicks_change'] == 'positive') { ?>
                                <b class="color-up"><i class="fa fa-caret-up"></i> <?php echo $dashboard_response['clicks_percentage']; ?>
                                    <?php } ?>%
                                    
                                </b> from last week</span>
                    </li>

                    <li class="col-xs-6 col-lg-2">
                        <span class="title"><i class="fa  fa-send"></i> Total Subscribers </span>
                        <h3><?php echo $dashboard_response['total_subscribers']; ?></h3>
			<span class="diff">
                            <?php if ($dashboard_response['subscribers_change'] == 'negative') { ?>
                            <b class="color-down"><i class="fa fa-caret-down"></i> <?php echo $dashboard_response['subscribers_percentage']; ?>
                                <?php } if ($dashboard_response['subscribers_change'] == 'positive') { ?>
                                <b class="color-up"><i class="fa fa-caret-up"></i> <?php echo $dashboard_response['subscribers_percentage']; ?>
                                    <?php } ?>%
                                    
                                </b> from last week</span>
                    </li>

                    

                    <li class="col-xs-6 col-lg-2">
                        <span class="title"><i class="fa  fa-cogs"></i> Campaigns </span>
                        <h3 class="color-up"><?php echo $dashboard_response['campaign_count']; ?></h3>
                        <span class="diff"><b class="color-down"></b> active this week</span>
                    </li>
					
                    <li class="col-xs-6 col-lg-2">
                        <span class="title"><i class="fa  fa-users"></i> Segments </span>
                        <h3 class="color-up"><?php echo $dashboard_response['segment_count']; ?></h3>
						<span class="diff"><b class="color-down"></b> created </span>
                    </li>

                    <li class="col-xs-6 col-lg-2">
                        <span class="title"><i class="fa fa-sitemap"></i> Sites</span>
                        <h3 class="color-up"><?php echo $dashboard_response['sites_count']; ?></h3>
						<span class="diff"><b class="color-down"></b>registered</span>
                    </li>
                </ul>
            </div>
            <!-- Top Stats End -->
	    <?php 

?>
	    
            <!-- Project Stats Start -->
            <div class="col-md-12 col-lg-12">
                <div class="panel panel-widget">
		  <?php if(count($dashboard_response['last_notifications']) > 0){?>
                    <div class="panel-title">
                        Last <span class="label label-info">5</span> Notifications
                       
                    </div>
                    <div class="panel-search">
                        <form>
                            <input type="text" class="form-control" placeholder="Search...">
                            <i class="fa fa-search icon"></i>
                        </form>
                    </div>
                    <div class="panel-body table-responsive">
			
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <td>#</td>
                                <td>Site</td>
                                <td>Message</td>
				<td>Sent</td>
                                <td>Delivered</td>
                                <td>Failed</td>
                                <td>Clicked</td>
				<td>Campaign</td>
                                <td>Created Date</td>
                            </tr>
                            </thead>
                            <tbody>
			    <?php $i=1;
			      foreach( $dashboard_response['last_notifications'] as $get_notifications_list){ 
				  $clicked_percentage=($get_notifications_list['total_clicked']/$get_notifications_list['total_sent'])*100;
			      ?>
                                <tr>
                                    <td><?php echo $i;?></td>
                                    <td><?php echo $get_notifications_list['siteURL']?></td>	
				     <td class="message">
					<div class="col-sm-10">
					    <h5 class="margin-t-0 font-bold">
						<a target="_blank" href="<?php echo  $get_notifications_list['url'];?>"><?php echo  $get_notifications_list['title'];?> </a>
					    </h5>
					    <p class="margin-b-5"><?php echo  $get_notifications_list['message'];?></p>
					    <a target="_blank" href="<?php echo  $get_notifications_list['url'];?>">
						<?php echo  $get_notifications_list['url'];?>
					    </a>
					  </div>
                                    </td> 

				   
				    <td><?php echo $get_notifications_list['total_sent']+$get_notifications_list['failed'];?></td>
                                    <td><?php echo $get_notifications_list['total_sent']?></td>
                                    <td><?php echo $get_notifications_list['failed'];?></td>
                                    <td><?php echo $get_notifications_list['total_clicked'];?> 
					<?php if($clicked_percentage>0){
					?>	
					  <b class="color-up margin-l-10"> <?php echo (int)$clicked_percentage; } else { ?> <b class="color-up margin-l-10">0 <?php } ?> %</b>
				    </td>
				    <td><?php if($get_notifications_list['campaign_flag']==0){ echo "No";}else{ echo "Yes";}?></td>
                                    <td><?php echo date("M d, Y H:i:s",strtotime($get_notifications_list['created_at']));?></td>
                                </tr>
                              <?php 
				      $i++;
			      } ?>  
                                                             
                            </tbody>
                        </table>
                    </div>
		      <?php }else{ echo "No result Found";} ?>
                </div>
            </div>
            <!-- Project Stats End -->
	  
        </div>
        <!-- Container End -->
    </div>
    <!-- Content End -->
<?php }else{

        Mage::app()->getResponse()->setRedirect(Mage::helper("adminhtml")->getUrl("adminhtml/pushassist_createaccount/index/"));
}?>