<?php 
$get_notifications = Mage::helper('pushassist')->get_notifications();

$check_api_key=Mage::app()->getStore()->getConfig('pushassistsection/general/apikey');
$check_secret_key=Mage::app()->getStore()->getConfig('pushassistsection/general/secretkey');
$account_response = Mage::helper('pushassist')->get_account_details();
$account_url='https://'.$account_response['account_name'].'.pushassist.com/login/';

if($check_api_key!='' && $check_secret_key != '') {

?>
<div id="Psidebar" >
  <ul>
    <li><a href="<?php echo $this->getUrl('*/pushassist_createaccount'); ?>">Create an Account</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_dashboard'); ?>">Dashboard</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_notificationmain'); ?>">Notifications</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_notificationsend'); ?>">Send Notification</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_segments'); ?>">Segments</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_createsegments'); ?>">Create Segment</a></li>
    <li><a href="<?php echo $this->getUrl('*/pushassist_subscribers'); ?>">Subscribers</a></li>
    <li><p><?php echo $account_response['planType'];?>&nbsp;&nbsp;<a href="<?php echo $account_url;?>" target="_blank">Upgrade Now</a> </p></li>
    <li><p>You have <?php echo $account_response['subscribers_remain'];?> subsribers left</p></li>
  </ul>
  </div>
<!-- Content Start -->
    <div id="pushassist" class="content dashboard clearfix">
        <!-- Start Page Header -->
        <div class="page-header">
            <h1 class="title">Notifications</h1>
        </div>
        <!-- End Page Header -->

        <!-- Container Start -->
        <div class="container-widget clearfix">
           

            <!-- Project Stats Start -->
            <div class="col-md-12 col-lg-12">
                <div class="panel panel-widget">
		  <?php if( count($get_notifications) > 0){ ?>
                    <div class="panel-title">
                        Last <span class="label label-info"><?php echo count($get_notifications);?></span> Notifications
                       
                    </div>
                    
                    <div class="panel-body table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <td>#</td>
                                <td>site url</td>                               
				<td>message</td>
				<td>Sent</td>
				<td>Delivered</td>
				<td>failed</td>
				<td>clicked</td>
				<td>Created Date</td>
                            </tr>
                            </thead>
                            <tbody>
			      <?php $i = 1;
				foreach($get_notifications as $get_notifications_list){
				$clicked_percentage=($get_notifications_list['total_clicked']/$get_notifications_list['total_sent'])*100;
				?>
                                <tr>
				
                                    <td><?php echo $i;?></td>
                                    <td><?php echo $get_notifications_list['siteurl']?></td>                                   
				    <td class="message">
					<div class="col-sm-3 table_image">
						<img src="<?php echo $get_notifications_list['logo']?>" alt="Notification Logo">
					</div>

					<div class="col-sm-8">
					    <h5 class="margin-t-0 font-bold">
						<a href="<?php echo  $get_notifications_list['url'];?>" target="_blank">
						  <?php echo  $get_notifications_list['title'];?></a>
					    </h5>
					    <p class="margin-b-5"><?php echo  $get_notifications_list['message'];?></p>
					    <a target="_blank" href="<?php echo $get_notifications_list['redirecturl'];?>"><?php echo $get_notifications_list['redirecturl'];?></a>
					</div>
				    </td>
				    
				    <td><?php echo $get_notifications_list['total_sent']+$get_notifications_list['failed'];?></td>
				    <td><?php echo $get_notifications_list['total_sent']?></td>
                                    <td><?php echo $get_notifications_list['failed'];?></td>
				    <td><?php echo $get_notifications_list['total_clicked'];?> 
					<?php if($clicked_percentage>0){
					?>	
					  <b class="color-up margin-l-10"> <?php echo (int)$clicked_percentage; } else { ?> <b class="color-up margin-l-10">0 <?php } ?> %</b>
				    </td>
				    
				    <td><?php echo date("M d, Y H:i:s",strtotime($get_notifications_list['created_at']));?></td>
                                </tr>
				  
                                <?php $i++;
				  } ?>
                                                              
                            </tbody>
                        </table>
                    </div>
		    <?php }else{ echo 'No result found';}?>
                </div>
            </div>
            <!-- Project Stats End -->

        </div>
        <!-- Container End -->

    </div>
    <!-- Content End -->
<?php 
}else{

Mage::app()->getResponse()->setRedirect(Mage::helper("adminhtml")->getUrl("adminhtml/pushassist_createaccount/index/"));
}
?>